/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ImgCompareSlider {}
}

declare global {


  interface HTMLImgCompareSliderElement extends Components.ImgCompareSlider, HTMLStencilElement {}
  var HTMLImgCompareSliderElement: {
    prototype: HTMLImgCompareSliderElement;
    new (): HTMLImgCompareSliderElement;
  };
  interface HTMLElementTagNameMap {
    'img-compare-slider': HTMLImgCompareSliderElement;
  }
}

declare namespace LocalJSX {
  interface ImgCompareSlider extends JSXBase.HTMLAttributes<HTMLImgCompareSliderElement> {}

  interface IntrinsicElements {
    'img-compare-slider': ImgCompareSlider;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


